import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserProvider from "@/components/UserProvider";
import NavBar from "@/components/Header"
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center justify-center w-screen h-screen bg-[#171D1C] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Header />
          <UserProvider>
              {children}
          </UserProvider>
      </body>
    </html>
  );
}
